jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set MAVEN_OPTS to increase stack size
        run: echo "MAVEN_OPTS=-Xss4m" >> $GITHUB_ENV

      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and analyze dependencies
        run: mvn clean install
